src/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, LoginView

from accounts.views import SettingsView, DisplayListView, DisplayLineUpdateView, DisplayLineCreateView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),
    # path('add-line/<int:pk>', DisplayLineCreateView.as_view(), name='add-line'),
    path('settings/<int:pk>', DisplayLineUpdateView.as_view(), name='settings'),
    path('', DisplayListView.as_view(), name='displays')
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('display/', include('displays.urls', namespace='display')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('displays.api_urls')),
    path('', include('accounts.urls', namespace='accounts')),
]

src/main/templates/main/layout.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{#    <script src="{{ STATIC_URL }}Highcharts-6.1.3/highcharts.js"></script>#}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
    <title>MyDisplay</title>
</head>
<body>

{% include 'main/navbar.html' %}

<div class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    {% block content %}


    {% endblock %}
</div>

<script src="{{ STATIC_URL }}jquery/jquery-3.2.1.min.js"></script>
<script src="{{ STATIC_URL }}popper/popper.js"></script>
<script src="{{ STATIC_URL }}bootstrap4/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}js/index.js"></script>
</body>
</html>

src/main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'accounts:displays' %}">MyDisplay</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
{#                <a class="nav-link {{ retrospectives_nav }}" href="{% url 'retrospectives:index' %}">Retrospectives</a>#}
            </li>
        </ul>

        <ul class="navbar-nav mr-right login">
            <li class="nav-item login-item">
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">{{ user|capfirst }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item {{ login_nav }}" href={% url 'accounts:logout' %}>Logout</a>
{#                        <a class="dropdown-item {{ settings_nav }}" href={% url 'accounts:settings' 1 %}>Settings</a>#}
                    </div>
                {% else %}
                    <a class="nav-link {{ login_nav }}" href={% url 'accounts:login' %}>Login</a>
                {% endif %}

                </li>
        </ul>


    </div>

</nav>